services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "15"
      USERNAME: "antaly"
      PASSWORD: "antaly520"
      RAM_SIZE: "32G"
      CPU_CORES: "8"
      DISK_SIZE: "400G"
      DISK2_SIZE: "100G"
      LANGUAGE: "Chinese"
      REGION: "zh_CN"       
      KEYBOARD: "cn"       
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m
